Algoritmo "Media idade"

Var

 idade1, idade2, mediaIdade : real
 nome1, nome2 : caractere



Inicio
escreval("Dados da primeira pessoa:")
escreva("Nome:")
leia(nome1)
escreva("idade:")
leia(idade1)
escreval("Dados da segunda pessoa:")
escreva("Nome:")
leia(nome2)
escreva("idade:")
leia(idade2)


mediaIdade <- (idade1 + idade2) / 2

escreval("A idade media de ", nome1, " e ", nome2, " é de ", mediaIdade, " anos!")


Fimalgoritmo